### PR TITLE
Belgium TaxRate and Jurisdiction

### PR DESCRIPTION
**Pull request by nWidart**
Adding :
- BelgiumValueAddedTax TaxRate
- Belgium Jurisdiction

### CODE REVIEW

**Comment by philipbrown** [comment]
Excellent! Thank you Nicolas :+1:

**Comment by nWidart** [comment]
Just question though, I don't know how it is in the UK, but in Belgium, Netherlands and France (probably more, more those I'm sure) there are multiple VAT amounts.
For instance:
- Belgium: 6%, 12%, 21%.
- Netherlands: 6%, 21%

How would that be implemented ?

**Comment by philipbrown** [comment]
Ah yeah, someone else has suggested adding a `setRate()` method to the `Product` object to overwrite the standard VAT amount.

I'll open up a separate issue for it :+1:

**Comment by nWidart** [comment]
Or just have a `VeryHightBelgiumValueAddedTax`, `HightBelgiumValueAddedTax`, etc, don't know though, might not be very explicit.

**Comment by philipbrown** [comment]
Yeah I don't think that would work for every country. I think it'll be better to have a default, and then allow the developer to override on a case-by-case basis.

**Comment by nWidart** [comment]
Yeah you're right, not very 'scalable'.

**Comment by philipbrown** [comment]
I've decided to rebuild this package piece by piece to incorporate all of this feedback.

I've also decided to get rid of having individual tax rate implementations and just have a generic `TaxRate` option that accepts a `float`.

Keep an eye out for the `dev` branch :smile:

**Comment by nWidart** [comment]
Damn, deleted everything. You don't joke with rebuilding the package! :stuck_out_tongue:

**Comment by philipbrown** [comment]
Haha yeah, I would rather start from a clean slate than get sentimental about what's already there :stuck_out_tongue:

**Pull request merged**
